import express from 'express';
import { v4 as uuidv4 } from 'uuid';
import { requireAdmin } from '../middleware/auth.js';
import { storageService } from '../services/storageService.js';
import { researchService } from '../services/researchService.js';
import { allowedParticipantIds, normalizeParticipantId, validateParticipantId } from '../utils/validators.js';
const router=express.Router();
const CONDITIONS=['scaffold','regular','unassigned'];
const csv=v=>{if(v==null)return '';const s=typeof v==='object'?JSON.stringify(v):String(v);return /[",\n\r]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;};
const sendJson=(res,name,data)=>{res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename=${name}`);res.send(JSON.stringify(data,null,2));};
const sendCsv=(res,name,headers,rows)=>{res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename=${name}`);res.send('\uFEFF'+[headers.join(','),...rows.map(r=>headers.map(h=>csv(r[h])).join(','))].join('\n'));};

router.post('/login',async(req,res)=>{try{const p=String(req.body?.password||'');if(!process.env.ADMIN_PASSWORD)return res.status(500).json({error:'服务器未配置ADMIN_PASSWORD'});if(p!==process.env.ADMIN_PASSWORD)return res.status(401).json({error:'密码错误，请重新输入。'});const id=`admin_${uuidv4().replace(/-/g,'')}`;await storageService.putObject(`admin-sessions/${id}.json`,JSON.stringify({created_at:new Date().toISOString(),expires_at:new Date(Date.now()+4*3600000).toISOString()}));res.cookie('admin_session',id,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',maxAge:4*3600000,path:'/'});res.json({success:true});}catch(e){res.status(500).json({error:'管理员登录服务异常'});}});
router.post('/logout',requireAdmin,async(req,res)=>{if(req.cookies?.admin_session)await storageService.deleteObject(`admin-sessions/${req.cookies.admin_session}.json`);res.clearCookie('admin_session',{path:'/'});res.json({success:true});});
router.get('/settings',requireAdmin,async(req,res)=>res.json(await researchService.getSettings()));
router.post('/settings',requireAdmin,async(req,res)=>{try{res.json(await researchService.saveSettings(req.body||{}));}catch(e){res.status(e.status||500).json({error:e.message});}});

async function ids(){const configured=allowedParticipantIds();const blobs=await storageService.listObjects('students/');const stored=blobs.map(x=>x.key.split('/').pop()?.replace('.json','')).filter(validateParticipantId);return [...new Set([...configured,...stored])].sort();}
async function formalIds(includeDemo=false){const out=[];for(const id of await ids()){const p=await researchService.getParticipant(id);if(includeDemo||!p.is_demo)out.push(id);}return out;}

async function summary(id){
  const [p,state,practice,r1,r2]=await Promise.all([researchService.getParticipant(id),researchService.getStudentState(id),researchService.getPractice(id),researchService.getRoundData(id,1),researchService.getRoundData(id,2)]);
  return {participant_id:id,condition:p.condition,grade:p.grade,is_demo:p.is_demo,current_stage:state.formal_stage,practice_completed:Boolean(practice.completed),round1_initial:Boolean(r1.initial?.locked),round1_chat:Boolean(r1.chat_session?.locked),round1_final:Boolean(r1.final?.locked),v2_retest:Boolean(r1.new_version?.retest_locked),round1_reflection:Boolean(r1.reflection?.locked),round2_initial:Boolean(r2.initial?.locked),round2_chat:Boolean(r2.chat_session?.locked),round2_final:Boolean(r2.final?.locked),v3_retest:Boolean(r2.new_version?.retest_locked),round2_reflection:Boolean(r2.reflection?.locked),last_active_at:p.last_active_at};
}

router.get('/participants',requireAdmin,async(req,res)=>{try{const rows=[];for(const id of await ids())rows.push(await summary(id));res.json(rows);}catch(e){res.status(500).json({error:'读取参与者列表失败'});}});
router.post('/participants/create-default',requireAdmin,async(req,res)=>{try{const rows=[];for(let i=1;i<=28;i++){const id=`P${String(i).padStart(2,'0')}`;rows.push(await researchService.createParticipant(id,{condition:'unassigned'}));}res.json({created:rows.length});}catch(e){res.status(500).json({error:e.message});}});
router.post('/participants/create-demo',requireAdmin,async(req,res)=>{try{await researchService.createParticipant('DEMO-S',{condition:'scaffold',is_demo:true});await researchService.createParticipant('DEMO-R',{condition:'regular',is_demo:true});res.json({created:['DEMO-S','DEMO-R']});}catch(e){res.status(500).json({error:e.message});}});
router.post('/participant/:participantId/condition',requireAdmin,async(req,res)=>{try{const id=normalizeParticipantId(req.params.participantId),condition=String(req.body?.condition||'unassigned');if(!validateParticipantId(id)||!CONDITIONS.includes(condition))return res.status(400).json({error:'编号或condition无效'});res.json(await researchService.setCondition(id,{condition,grade:req.body?.grade},'admin',Boolean(req.body?.confirm)));}catch(e){res.status(e.status||500).json({error:e.message,code:e.code});}});
router.post('/participants/bulk',requireAdmin,async(req,res)=>{try{const lines=String(req.body?.text||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean),result=[];for(const line of lines){const [rawId,rawCondition='unassigned',...gradeParts]=line.split(/[\t, ]+/),id=normalizeParticipantId(rawId),condition=String(rawCondition).toLowerCase(),grade=gradeParts.join(' ');if(!validateParticipantId(id)||!CONDITIONS.includes(condition)){result.push({line,status:'invalid'});continue;}await researchService.createParticipant(id,{condition,grade});result.push({participant_id:id,condition,status:'ok'});}res.json({result});}catch(e){res.status(500).json({error:e.message});}});
router.get('/participant/:participantId',requireAdmin,async(req,res)=>{try{res.json(await researchService.getCompleteParticipantData(normalizeParticipantId(req.params.participantId)));}catch(e){res.status(500).json({error:'读取参与者资料失败'});}});

async function completeRows(includeDemo=false){const rows=[];for(const id of await formalIds(includeDemo))rows.push(await researchService.getCompleteParticipantData(id));return rows;}
router.get('/export/all.json',requireAdmin,async(req,res)=>sendJson(res,'research_all.json',await completeRows(req.query.include_demo==='1')));
router.get('/export/participant/:participantId.json',requireAdmin,async(req,res)=>sendJson(res,`${normalizeParticipantId(req.params.participantId)}.json`,await researchService.getCompleteParticipantData(normalizeParticipantId(req.params.participantId))));

router.get('/export/participants.csv',requireAdmin,async(req,res)=>{const rows=[];for(const id of await formalIds(req.query.include_demo==='1'))rows.push(await summary(id));sendCsv(res,'participants.csv',['participant_id','condition','grade','is_demo','current_stage','practice_completed','round1_initial','round1_chat','round1_final','v2_retest','round1_reflection','round2_initial','round2_chat','round2_final','v3_retest','round2_reflection','last_active_at'],rows);});

function flatVersion(prefix,v={}){return{[`${prefix}_photo_ids`]:(v.photos||[]).map(x=>x.file_name).join('|'),[`${prefix}_test_1`]:v.performance?.test_1??'',[`${prefix}_test_2`]:v.performance?.test_2??'',[`${prefix}_test_3`]:v.performance?.test_3??'',[`${prefix}_mean`]:v.performance?.mean_descent_time??'',[`${prefix}_opened`]:v.observations?.opened??'',[`${prefix}_sway`]:v.observations?.sway??'',[`${prefix}_rotation`]:v.observations?.rotation??'',[`${prefix}_drift`]:v.observations?.drift??'',[`${prefix}_stable_canopy`]:v.observations?.stable_canopy??'',[`${prefix}_other_observation`]:v.observations?.other_observation??''};}
function flatRound(prefix,r={}){return{[`${prefix}_initial_problem`]:r.initial?.initial_problem??'',[`${prefix}_initial_evidence`]:r.initial?.initial_evidence??'',[`${prefix}_initial_reason`]:r.initial?.initial_reason??'',[`${prefix}_chat_started_at`]:r.chat_session?.started_at??'',[`${prefix}_chat_ended_at`]:r.chat_session?.ended_at??'',[`${prefix}_chat_duration`]:r.chat_session?.chat_duration_seconds??'',[`${prefix}_user_turn_count`]:r.chat_session?.user_turn_count??0,[`${prefix}_assistant_turn_count`]:r.chat_session?.assistant_turn_count??0,[`${prefix}_agent_id`]:r.chat_session?.bot_id??'',[`${prefix}_prompt_version`]:r.chat_session?.prompt_version??'',[`${prefix}_model`]:r.chat_session?.model??'',[`${prefix}_final_problem`]:r.final?.final_problem??'',[`${prefix}_final_evidence`]:r.final?.final_evidence??'',[`${prefix}_final_reason`]:r.final?.final_reason??'',[`${prefix}_revision_decision`]:r.final?.revision_decision??'',[`${prefix}_revision_reason`]:r.final?.revision_reason??'',[`${prefix}_alternative_considered`]:r.alternative?.alternative_considered??'',[`${prefix}_alternative_text`]:r.alternative?.alternative_text??'',[`${prefix}_alternative_reject_reason`]:r.alternative?.alternative_reject_reason??'',[`${prefix}_actual_revision`]:r.revision?.actual_revision??'',[`${prefix}_revision_difference`]:r.revision?.revision_difference??'',[`${prefix}_self_tried`]:r.self_verification?.self_tried??'',[`${prefix}_self_goal`]:r.self_verification?.self_goal??'',[`${prefix}_self_method`]:r.self_verification?.self_method??'',[`${prefix}_self_result`]:r.self_verification?.self_result??'',[`${prefix}_reflection`]:JSON.stringify(r.reflection||{})};}
router.get('/export/formal.csv',requireAdmin,async(req,res)=>{const rows=[];for(const id of await formalIds(req.query.include_demo==='1')){const d=await researchService.getCompleteParticipantData(id);rows.push({participant_id:id,condition:d.participant.condition,grade:d.participant.grade,...flatVersion('perf_v1',d.round1.evidence||{}),...flatRound('round1',d.round1),...flatVersion('perf_v2',d.round1.new_version||{}),...flatRound('round2',d.round2),...flatVersion('perf_v3',d.round2.new_version||{})});}const headers=[...new Set(rows.flatMap(r=>Object.keys(r)))];sendCsv(res,'formal_rounds.csv',headers,rows);});
router.get('/export/practice.csv',requireAdmin,async(req,res)=>{const rows=[];for(const id of await formalIds(req.query.include_demo==='1')){const p=await researchService.getPractice(id);rows.push({participant_id:id,practice_revision_idea:p.practice_revision_idea||'',practice_evidence:p.practice_evidence||'',before_submitted_at:p.before_submitted_at||'',chat_completed:p.chat_completed||false,completed_at:p.completed_at||''});}sendCsv(res,'practice.csv',Object.keys(rows[0]||{participant_id:''}),rows);});
router.get('/export/chat_messages.csv',requireAdmin,async(req,res)=>{const rows=[];for(const id of await formalIds(req.query.include_demo==='1'))for(const scope of ['round1','round2'])rows.push(...await researchService.getMessages(id,scope));sendCsv(res,'chat_messages.csv',['participant_id','scope','message_index','message_id','role','content','conversation_id','chat_id','bot_id','prompt_version','model','created_at'],rows);});
router.get('/export/practice_chat_messages.csv',requireAdmin,async(req,res)=>{const rows=[];for(const id of await formalIds(req.query.include_demo==='1'))rows.push(...await researchService.getMessages(id,'practice'));sendCsv(res,'practice_chat_messages.csv',['participant_id','scope','message_index','message_id','role','content','conversation_id','chat_id','bot_id','prompt_version','model','created_at'],rows);});
export default router;
